/**
 * Generated shape of the public schema.
 *
 * Kept by hand for the MVP; once the schema settles, regenerate with:
 *   npm run db:types
 */
import type { Company, ProfileType } from "@/lib/classification";

export type ProcessingStatus =
  | "UPLOADING"
  | "PENDING"
  | "PROCESSING"
  | "COMPLETED"
  | "FAILED";

export type Profile = {
  id: string;
  full_name: string;
  /** Generated column: lower-cased and accent-stripped. Read-only. */
  full_name_normalized: string;
  email: string | null;
  phone: string | null;
  position: string | null;
  department: string | null;
  education: string | null;
  experience_years: number | null;
  summary: string | null;
  /** HR/business classification, assigned by hand. Null until someone sets it. */
  profile_type: ProfileType | null;
  /** Empresa the person belongs to. Never derived — see src/lib/classification.ts. */
  company: Company | null;
  created_at: string;
  updated_at: string;
};

export type ProfileAssessment = {
  id: string;
  profile_id: string;
  document_id: string;
  report_date: string | null;
  dominance: number | null;
  influence: number | null;
  steadiness: number | null;
  control: number | null;
  adaptacion_laboral: number | null;
  conducta_bajo_presion: number | null;
  imagen_propia: number | null;
  raw_scores: unknown;
  conductas_observables_1: string | null;
  conductas_observables_2: string | null;
  conductas_observables_3: string | null;
  motivadores: string | null;
  entorno_laboral_ideal: string | null;
  otros_comentarios: string | null;
  created_at: string;
  updated_at: string;
};

export type DocumentRow = {
  id: string;
  profile_id: string | null;
  file_name: string;
  storage_path: string;
  file_size: number | null;
  mime_type: string | null;
  processing_status: ProcessingStatus;
  processing_error: string | null;
  created_at: string;
  updated_at: string;
};

export type Trait = {
  id: string;
  profile_id: string;
  code: string;
  label: string;
  /** Which document produced this row; null when a person typed it in. */
  source_document_id: string | null;
  created_at: string;
};

export type TraitInsert = Omit<Trait, "id" | "created_at" | "source_document_id"> & {
  source_document_id?: string | null;
};

/** Arguments and result of the apply_document_analysis() RPC. */
export type ApplyDocumentAnalysisArgs = {
  p_document_id: string;
  p_full_name: string;
  p_report_date: string | null;
  p_scores: Record<string, unknown>;
  p_sections: Record<string, string | null>;
  p_capabilities: { code: string; label: string }[];
  p_attitudes: { code: string; label: string }[];
};

export type ApplyDocumentAnalysisResult = {
  profile_id: string;
  profile_created: boolean;
};

type Table<Row, Insert = Partial<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Partial<Insert>;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<
        Profile,
        // full_name_normalized is generated by Postgres and must never be written.
        // The classification columns are optional: a profile is created without
        // one and gets it later, from the form on the detail page.
        Omit<
          Profile,
          "id" | "created_at" | "updated_at" | "full_name_normalized" | "profile_type" | "company"
        > & {
          id?: string;
          profile_type?: ProfileType | null;
          company?: Company | null;
        }
      >;
      profile_assessments: Table<
        ProfileAssessment,
        Omit<ProfileAssessment, "id" | "created_at" | "updated_at">
      >;
      documents: Table<
        DocumentRow,
        Omit<DocumentRow, "created_at" | "updated_at" | "processing_status" | "processing_error"> & {
          processing_status?: ProcessingStatus;
          processing_error?: string | null;
        }
      >;
      // source_document_id is omitted when a person enters a trait by hand.
      profile_capabilities: Table<Trait, TraitInsert>;
      profile_attitudes: Table<Trait, TraitInsert>;
    };
    Views: Record<never, never>;
    Functions: {
      apply_document_analysis: {
        Args: ApplyDocumentAnalysisArgs;
        Returns: ApplyDocumentAnalysisResult;
      };
    };
    Enums: { processing_status: ProcessingStatus };
    CompositeTypes: Record<never, never>;
  };
};
